ALTER TABLE work_runs ADD COLUMN IF NOT EXISTS input_tokens BIGINT DEFAULT 0;
ALTER TABLE work_runs ADD COLUMN IF NOT EXISTS output_tokens BIGINT DEFAULT 0;
ALTER TABLE work_runs ADD COLUMN IF NOT EXISTS cache_read_tokens BIGINT DEFAULT 0;
ALTER TABLE work_runs ADD COLUMN IF NOT EXISTS cache_write_tokens BIGINT DEFAULT 0;
ALTER TABLE work_runs ADD COLUMN IF NOT EXISTS model_used TEXT;