ALTER TABLE project_configs
    ADD COLUMN IF NOT EXISTS agents_md TEXT NOT NULL DEFAULT '';

ALTER TABLE work_runs
    ADD COLUMN IF NOT EXISTS repo_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS agents_md TEXT NOT NULL DEFAULT '';
