pub(crate) mod github;
pub(crate) mod project_configs;
pub(crate) mod state;
pub(crate) mod teams;
pub(crate) mod work_runs;
pub(crate) mod workers;

use hmac::{Hmac, Mac};
use sha2::Sha256;
use std::sync::Arc;

use uuid::Uuid;

use crate::app_state::AppState;
use crate::db::auth::AuthRepository;
use crate::db::github_app::GithubAppRepository;
use crate::db::model_providers::ModelProvidersRepository;
use crate::db::project_configs::ProjectConfigsRepository;
use crate::db::project_usage::ProjectUsageRepository;
use crate::db::provider_configs::IntegrationProvidersRepository;
use crate::db::task_augmentations::TaskAugmentationsRepository;
use crate::db::teams::TeamsRepository;
use crate::db::users::UsersRepository;
use crate::db::work_run_events::WorkRunEventsRepository;
use crate::db::work_runs::queries::InsertWorkRunParams;
use crate::db::work_runs::WorkRunsRepository;
use crate::db::workers::WorkersRepository;
use crate::models::teams::model::{DEFAULT_PROMPT_TEMPLATE, DEFAULT_REVIEW_PROMPT_TEMPLATE};
use crate::models::work_runs::model::{WorkRunStatus, WorkRunType};
use crate::services::auth::service::AuthService;
use crate::services::dispatcher::cancel_store::InMemoryCancelStore;
use crate::services::dispatcher::dispatch_store::InMemoryDispatchStore;
use crate::services::github_app::service::webhooks::GithubWebhookService;
use crate::services::github_app::service::GithubAppManager;
use crate::services::github_app::webhook_store::GithubWebhookStore;
use crate::services::model_providers::auth::device_flow::InMemoryDeviceFlowStore;
use crate::services::model_providers::auth::encryption::SecretCipher;
use crate::services::model_providers::auth::openai_chatgpt::OpenAiChatGptDeviceAuthProvider;
use crate::services::model_providers::catalog::ModelCatalogClient;
use crate::services::model_providers::service::ModelProvidersService;
use crate::services::project_configs::service::ProjectConfigsService;
use crate::services::provider_configs::service::IntegrationProvidersService;
use crate::services::task_board::service::TaskBoardService;
use crate::services::teams::service::TeamsService;
use crate::services::users::service::UsersService;
use crate::services::work_run_events::service::WorkRunEventsService;
use crate::services::work_runs::service::WorkRunsService;
use crate::services::workers::registration_code_store::InMemoryCodeStore;
use crate::services::workers::service::WorkersService;

pub const DEFAULT_TEAM_ID: Uuid = Uuid::from_u128(1);
pub const GITHUB_WEBHOOK_SECRET: &str = "webhook-test-secret";
