name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:

env:
  SQLX_OFFLINE: true
  CARGO_INCREMENTAL: 0

jobs:
  ci-pass:
    name: CI succeeded
    runs-on: self-hosted
    if: always()
    needs:
      - lint
      - test
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Check whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}

  lint:
    name: Format & Lint & Type-Check
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Build Dependencies
        run: |
          sudo dpkg --configure -a
          sudo apt update && sudo apt install pkg-config libssl-dev clang -y
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - uses: Swatinem/rust-cache@v2
      - run: pnpm install
      - name: Run format, lint, and type-check
        run: pnpm run validate

  test:
    name: Test
    runs-on: self-hosted
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vulcanum_db
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 172.17.0.1:5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Build Dependencies
        run: |
          sudo dpkg --configure -a
          sudo apt update && sudo apt install pkg-config libssl-dev clang -y
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - uses: Swatinem/rust-cache@v2
      - name: Install SQLx CLI
        run: cargo install sqlx-cli
      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@172.17.0.1:5432/vulcanum_db
        run: sqlx migrate run --source server/migrations
      - run: pnpm install
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@172.17.0.1:5432/vulcanum_db
        run: pnpm run test
