name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-cli:
    name: Build CLI
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Build Dependencies
        run: sudo apt update && sudo apt install pkg-config libssl-dev clang -y

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build CLI (release)
        run: cargo build --release --bin vulcanum

      - name: Build Worker Server (release)
        run: cargo build --release --bin vulcanum-server

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v3
        with:
          files: |
            target/release/vulcanum
            target/release/vulcanum-server
